# Generated by Django 2.0.4 on 2018-04-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField(verbose_name='createdAt')),
            ],
        ),
    ]
